#!/usr/bin/env node
const commands = ['new', 'get', 'complete', 'help']
// const chalk = require('chalk')
const args = process.argv
const fs = require("fs")


// usage represents the help guide
const usage = function() {
  const usageText = `
  todo helps you manage you todo tasks.

  usage:
    todo <command>

    commands can be:

    new:      used to create a new todo
    get:      used to retrieve your todos
    complete: used to mark a todo as complete
    help:     used to print the usage guide
  `

  console.log(usageText)
}

// used to log errors to the console in red color
function errorLog(error) {
  const eLog = error
  console.log(eLog)
}

// we make sure the length of the arguments is exactly three
if (args.length > 3) {
  errorLog(`only one argument can be accepted`)
  usage()
}

if (commands.indexOf(args[2]) == -1) {
  errorLog('invalid command passed')
  usage()
}

function newTodo() {
  var running = `npx playwright test`
  fs.writeFileSync("run_cmd.sh", running)
}

switch(args[2]) {
  case 'help':
    usage()
    break
  case 'new':
    newTodo();
    break
  case 'get':
    break
  case 'complete':
    break
  default:
    errorLog('invalid command passed')
    usage()
}

